parameters:
  file_transfer:
    servers:
      example_server_id_1:
        address: 127.0.0.1
        username: example_user_name_1
        password: example_user_password_1
      example_server_id_2:
        address: 127.0.0.1
        username: example_user_name_2
        password: example_user_password_2
  # copy these lines to your pimcore app/config/config.yml and change them to match your real server configs
